Inventory/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InterfaceDAL;
using Inventory.Entity;
namespace Inventory.Controllers
{
    public class ImageupController : Controller
    {

        private readonly MyCustomRepository<Image_Table> _Image_TableRepository;

        public ImageupController()
        {
            _Image_TableRepository = new MyCustomRepository<Image_Table>();
        }
        // GET: Image
        public ActionResult Index()
        {
            return View(_Image_TableRepository.GetAllData());
        }


        public ActionResult Uploadim(HttpPostedFileBase file)
        {
            if (file != null)
            {
                string name = Path.GetFileName(file.FileName);
                string filePath = "~/upload/" + name;

                file.SaveAs(Server.MapPath(filePath));
                _Image_TableRepository.InsertRecord(new Image_Table { Title = name, image = filePath });
                _Image_TableRepository.SaveRecord();
            }
            return RedirectToAction("Index");
        }
    }


}

Inventory/Views/Imageup/Index.cshtml
@model IEnumerable<Inventory.Entity.Image_Table>
@{
    ViewBag.Title = "Upload Image";
    WebGrid webGrid = new WebGrid(source: Model, canSort: false, canPage: false);
}

<h2>Index</h2>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/themes/start/jquery-ui.css" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js"></script>


<div class="row">
    <div class="col-md-4">
        <h2>Upload Image</h2>
        <p>
            @using (Html.BeginForm("Uploadim", "Imageup", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                <input type="file" name="file" />
                <input type="submit" name="btnUpload" value="Upload File" />


            }


            <hr />
        </p>
    </div>

    <div class="col-md-4">
        <h2>List Image</h2>
        <p>
            @webGrid.GetHtml(
       htmlAttributes: new { @id = "WebGrid" },
       columns: webGrid.Columns(
           webGrid.Column("Id", "ID"),
           webGrid.Column("Title", "NAME"),
           webGrid.Column("Image", "PHOTO", format:@<text><img alt="@item.Title" src="@Url.Content(item.Image)" style="width:200px; height:auto; padding:30px;" /></text>)))
        </p>
    </div>
</div>